{% set name = "pyrsm" %}
{% set version = "0.8.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrsm-{{ version }}.tar.gz
  sha256: f19aba14f1c4952471bd8d201d854e2a43a5d14eae44d489b0e8908b4876a40a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - numpy >=1.17.3
    - pandas >=0.25.2
    - polars >=0.17.14
    - seaborn >=0.9.0
    - matplotlib-base >=3.1.1
    - statsmodels >=0.10.1
    - scipy >=1.4.1
    - scikit-learn >=1.0.2
    - IPython >=8.0.1
    - shiny >=0.3.3
    - uvicorn >=0.20.0
    - nest-asyncio >=1.5.6
    - black >=22.6.0
    - python >=3.6
test:
  imports:
    - pyrsm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pyrsm/
  summary: Python functions for Customer Analytics at the Rady School of Management (RSM)
  dev_url: https://github.com/vnijs/pyrsm
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vnijs
